-- Generated by Gemini 2026/04/20
local color_too_long = "1;31"

local git_len_classifier = clink.classifier()

function git_len_classifier:classify(commands)
    for _, command in ipairs(commands) do
        local line_state = command.line_state
        local classifications = command.classifications
        local line = line_state:getline()

        -- Only handle git commit commands
        if line:find("^git%s+commit") then
            -- Capture -m/--message content and its start
            -- Tolerates an unclosed quote while typing
            local message_start, message = line:match([[[%-]%-?m%w*%s+["']()(.-)["']?%s*$]])

            if message and #message > 50 then
                -- Overflow starts at the 51st character
                local highlight_start = message_start + 50
                local highlight_end = message_start + #message - 1

                if highlight_start <= highlight_end then
                    local length = highlight_end - highlight_start + 1
                    classifications:applycolor(highlight_start, length, color_too_long)
                end
            end
        end
    end
    return false
end

