hwdec=auto
# https://github.com/mpv-player/mpv/issues/9235
# hwdec=dxva2
save-position-on-quit
demuxer-readahead-secs=20
cache-secs=3600
cache=yes
demuxer-max-bytes=512MiB

ytdl-format="bestvideo[height<=?1080][fps<=?60][vcodec!=vp9]+bestaudio/best"
ytdl-raw-options=downloader-args="ffmpeg_i1:-reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 3600",downloader-args="ffmpeg_i2:-reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 3600",downloader-args="ffmpeg_i0:-reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 3600",sub-lang="en",write-sub=,write-auto-sub=
stream-lavf-o-append=reconnect_on_http_error=4xx,5xx
stream-lavf-o-append=reconnect_delay_max=3600
stream-lavf-o-append=reconnect_streamed=yes

sub-font-size=53
sub-font='Noto Sans JP Bold'

[Downmix_Audio_5_1]
profile-cond=get("audio-params/channel-count") >= 5 and get("audio-params/channel-count") < 7
profile-restore=copy-equal
volume-max=200
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE"
